# Generated by Django 4.1.4 on 2022-12-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlg_id', models.IntegerField(default=0, verbose_name='Телеграм ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм username')),
                ('org_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации')),
                ('telephone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_active_staff', models.BooleanField(default=False, verbose_name='Активный персонал')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_link', models.URLField(verbose_name='Ссылка на обращение')),
                ('last_call', models.DateTimeField(auto_now=True, verbose_name='Крайнее обращение')),
                ('last_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_bot_api.botuser', verbose_name='Крайний оператор')),
            ],
        ),
    ]
