# Generated by Django 4.1.4 on 2022-12-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersAppeal',
            new_name='Appeal',
        ),
    ]
