# Generated by Django 4.1.4 on 2022-12-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot_api', '0002_rename_usersappeal_appeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['-id'], 'verbose_name': 'Обращение поддержки', 'verbose_name_plural': 'Обращения поддержки'},
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-id'], 'verbose_name': 'Пользователь поддержки', 'verbose_name_plural': 'Пользователи поддержки'},
        ),
        migrations.AlterModelTable(
            name='appeal',
            table='Таблица обращений поддержки',
        ),
        migrations.AlterModelTable(
            name='botuser',
            table='Таблица пользователей поддержки',
        ),
    ]
