# Generated by Django 4.1.4 on 2022-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot_api', '0003_alter_appeal_options_alter_botuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='author',
            field=models.IntegerField(default=0, verbose_name='Автор обращения(TLG ID)'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='last_operator',
            field=models.IntegerField(default=0, verbose_name='Крайний оператор(TLG ID)'),
        ),
    ]
