# Generated by Django 4.1.4 on 2022-12-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot_api', '0004_appeal_author_alter_appeal_last_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
                ('tlg_msg_id', models.IntegerField(default=0, verbose_name='ID поста')),
                ('link_to_post', models.URLField(verbose_name='Ссылка на пост')),
            ],
            options={
                'verbose_name': 'База знаний',
                'verbose_name_plural': 'База знаний',
                'db_table': 'Таблица базы знаний',
                'ordering': ['id'],
            },
        ),
    ]
